"""Add prep_time, cook_time, etc. to Recipe model

Revision ID: e20ff6feb253
Revises: 
Create Date: 2024-09-08 11:27:25.215289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20ff6feb253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prep_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cook_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('yield_', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('variations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('main_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extra_images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('related', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('related')
        batch_op.drop_column('extra_images')
        batch_op.drop_column('main_image')
        batch_op.drop_column('variations')
        batch_op.drop_column('description')
        batch_op.drop_column('yield_')
        batch_op.drop_column('total_time')
        batch_op.drop_column('cook_time')
        batch_op.drop_column('prep_time')

    # ### end Alembic commands ###
